//! Golden reconcile tests — cluster-free.
//!
//! These build Gateway API objects in memory, translate them to Flow text, and
//! assert both the exact generated source (golden) and that installing it into a
//! real [`ConfigStore`] yields the expected typed config. No apiserver is
//! touched: the reconcile core ([`pulsate_k8s::install`] / [`to_flow`]) is pure.

use pulsate_config::ConfigStore;
use pulsate_k8s::crd::{
    Gateway, GatewayClass, GatewayClassSpec, GatewaySpec, HTTPBackendRef, HTTPPathMatch, HTTPRoute,
    HTTPRouteMatch, HTTPRouteRule, HTTPRouteSpec, Listener, ParentRef,
};
use pulsate_k8s::{install, to_flow, CONTROLLER_NAME};

// ---- builders -------------------------------------------------------------

fn class(name: &str, controller: &str) -> GatewayClass {
    GatewayClass::new(
        name,
        GatewayClassSpec {
            controller_name: controller.to_string(),
        },
    )
}

fn listener(name: &str, host: Option<&str>, port: u16, proto: &str) -> Listener {
    Listener {
        name: name.to_string(),
        hostname: host.map(str::to_string),
        port,
        protocol: proto.to_string(),
    }
}

fn gateway(ns: &str, name: &str, class_name: &str, listeners: Vec<Listener>) -> Gateway {
    let mut g = Gateway::new(
        name,
        GatewaySpec {
            gateway_class_name: class_name.to_string(),
            listeners,
        },
    );
    g.metadata.namespace = Some(ns.to_string());
    g
}

fn parent(name: &str) -> ParentRef {
    ParentRef {
        name: name.to_string(),
        namespace: None,
        section_name: None,
    }
}

fn prefix_match(path: &str) -> HTTPRouteMatch {
    HTTPRouteMatch {
        path: Some(HTTPPathMatch {
            match_type: "PathPrefix".to_string(),
            value: path.to_string(),
        }),
        method: None,
    }
}

fn backend(name: &str, port: u16) -> HTTPBackendRef {
    HTTPBackendRef {
        name: name.to_string(),
        namespace: None,
        port: Some(port),
        weight: None,
    }
}

fn route(
    ns: &str,
    name: &str,
    parents: Vec<ParentRef>,
    hostnames: Vec<&str>,
    rules: Vec<HTTPRouteRule>,
) -> HTTPRoute {
    let mut r = HTTPRoute::new(
        name,
        HTTPRouteSpec {
            parent_refs: parents,
            hostnames: hostnames.into_iter().map(str::to_string).collect(),
            rules,
        },
    );
    r.metadata.namespace = Some(ns.to_string());
    r
}

// ---- tests ----------------------------------------------------------------

#[test]
fn single_http_route_golden_text_and_config() {
    let classes = vec![class("pulsate", CONTROLLER_NAME)];
    let gateways = vec![gateway(
        "default",
        "web",
        "pulsate",
        vec![listener("http", Some("app.example.com"), 80, "HTTP")],
    )];
    let routes = vec![route(
        "default",
        "app",
        vec![parent("web")],
        vec!["app.example.com"],
        vec![HTTPRouteRule {
            matches: vec![prefix_match("/api")],
            backend_refs: vec![backend("api-svc", 8080)],
        }],
    )];

    let text = to_flow(&classes, &gateways, &routes, CONTROLLER_NAME);

    let expected = "\
# Generated by the pulsate-k8s Gateway API controller. Do not edit.

upstream up_default_app_0 {
  target http://api-svc.default.svc:8080
}

site app.example.com {
  tls off
  route /api/* ~> proxy(@up_default_app_0)
}
";
    assert_eq!(text, expected, "generated Flow text drifted");

    // And it installs cleanly into the live store.
    let store = ConfigStore::load("seed", "").expect("empty seed compiles");
    install(&store, &classes, &gateways, &routes, CONTROLLER_NAME).expect("installs");

    let gen = store.current();
    assert_eq!(gen.config.upstreams.len(), 1);
    assert_eq!(gen.config.upstreams[0].name, "up_default_app_0");
    assert_eq!(
        gen.config.upstreams[0].targets[0].url,
        "http://api-svc.default.svc:8080"
    );
    assert_eq!(gen.config.sites.len(), 1);
    let site = &gen.config.sites[0];
    assert_eq!(site.hosts[0].pattern, "app.example.com");
    assert_eq!(site.tls, pulsate_config::TlsMode::Off);
    let handler = site.routes[0].handler.as_ref().unwrap();
    assert_eq!(handler.name(), "proxy");
}

#[test]
fn https_listener_exact_match_and_method_predicate() {
    let classes = vec![class("pulsate", CONTROLLER_NAME)];
    let gateways = vec![gateway(
        "prod",
        "edge",
        "pulsate",
        vec![listener("https", Some("api.example.com"), 443, "HTTPS")],
    )];
    let routes = vec![route(
        "prod",
        "svc",
        vec![parent("edge")],
        vec!["api.example.com"],
        vec![HTTPRouteRule {
            matches: vec![HTTPRouteMatch {
                path: Some(HTTPPathMatch {
                    match_type: "Exact".to_string(),
                    value: "/healthz".to_string(),
                }),
                method: Some("get".to_string()),
            }],
            backend_refs: vec![backend("health", 9000)],
        }],
    )];

    let text = to_flow(&classes, &gateways, &routes, CONTROLLER_NAME);
    assert!(
        text.contains("  tls auto\n"),
        "HTTPS should map to tls auto"
    );
    assert!(
        text.contains("route = /healthz [method=GET] ~> proxy(@up_prod_svc_0)"),
        "exact + method predicate not rendered:\n{text}"
    );

    let store = ConfigStore::load("seed", "").unwrap();
    install(&store, &classes, &gateways, &routes, CONTROLLER_NAME).expect("installs");
    let gen = store.current();
    let route = &gen.config.sites[0].routes[0];
    assert_eq!(route.kind, pulsate_config::MatchKind::Exact);
    assert_eq!(route.method.as_deref(), Some("GET"));
    assert_eq!(gen.config.sites[0].tls, pulsate_config::TlsMode::Auto);
}

#[test]
fn weighted_backends_become_weighted_targets() {
    let classes = vec![class("pulsate", CONTROLLER_NAME)];
    let gateways = vec![gateway(
        "default",
        "web",
        "pulsate",
        vec![listener("http", Some("split.example.com"), 80, "HTTP")],
    )];
    let routes = vec![route(
        "default",
        "canary",
        vec![parent("web")],
        vec!["split.example.com"],
        vec![HTTPRouteRule {
            matches: vec![prefix_match("/")],
            backend_refs: vec![
                HTTPBackendRef {
                    name: "v1".to_string(),
                    namespace: None,
                    port: Some(80),
                    weight: Some(9),
                },
                HTTPBackendRef {
                    name: "v2".to_string(),
                    namespace: None,
                    port: Some(80),
                    weight: Some(1),
                },
            ],
        }],
    )];

    let text = to_flow(&classes, &gateways, &routes, CONTROLLER_NAME);
    assert!(
        text.contains("target http://v1.default.svc:80 weight=9"),
        "{text}"
    );
    // weight=1 is the default and is omitted for cleanliness.
    assert!(text.contains("target http://v2.default.svc:80\n"), "{text}");

    let store = ConfigStore::load("seed", "").unwrap();
    install(&store, &classes, &gateways, &routes, CONTROLLER_NAME).expect("installs");
    let up = &store.current().config.upstreams[0];
    assert_eq!(up.targets.len(), 2);
    assert_eq!(up.targets[0].weight, 9);
    assert_eq!(up.targets[1].weight, 1);
}

#[test]
fn routes_sharing_a_host_aggregate_without_collision() {
    // Two HTTPRoutes attach to the same gateway/host. They must fold into ONE
    // site (a host collision would be a hard compile error).
    let classes = vec![class("pulsate", CONTROLLER_NAME)];
    let gateways = vec![gateway(
        "default",
        "web",
        "pulsate",
        vec![listener("http", Some("shared.example.com"), 80, "HTTP")],
    )];
    let routes = vec![
        route(
            "default",
            "a",
            vec![parent("web")],
            vec!["shared.example.com"],
            vec![HTTPRouteRule {
                matches: vec![prefix_match("/a")],
                backend_refs: vec![backend("svc-a", 80)],
            }],
        ),
        route(
            "default",
            "b",
            vec![parent("web")],
            vec!["shared.example.com"],
            vec![HTTPRouteRule {
                matches: vec![prefix_match("/b")],
                backend_refs: vec![backend("svc-b", 80)],
            }],
        ),
    ];

    let store = ConfigStore::load("seed", "").unwrap();
    install(&store, &classes, &gateways, &routes, CONTROLLER_NAME).expect("no host collision");
    let gen = store.current();
    assert_eq!(gen.config.sites.len(), 1, "must be one aggregated site");
    assert_eq!(gen.config.sites[0].routes.len(), 2);
    assert_eq!(gen.config.upstreams.len(), 2);
}

#[test]
fn unmanaged_class_is_ignored() {
    // A GatewayClass for some other controller must be skipped entirely.
    let classes = vec![class("other", "someone-else.io/controller")];
    let gateways = vec![gateway(
        "default",
        "web",
        "other",
        vec![listener("http", Some("nope.example.com"), 80, "HTTP")],
    )];
    let routes = vec![route(
        "default",
        "app",
        vec![parent("web")],
        vec!["nope.example.com"],
        vec![HTTPRouteRule {
            matches: vec![prefix_match("/")],
            backend_refs: vec![backend("svc", 80)],
        }],
    )];

    let store = ConfigStore::load("seed", "").unwrap();
    install(&store, &classes, &gateways, &routes, CONTROLLER_NAME).expect("installs empty");
    let gen = store.current();
    assert!(gen.config.sites.is_empty());
    assert!(gen.config.upstreams.is_empty());
}

#[test]
fn rule_without_backends_is_skipped() {
    let classes = vec![class("pulsate", CONTROLLER_NAME)];
    let gateways = vec![gateway(
        "default",
        "web",
        "pulsate",
        vec![listener("http", Some("h.example.com"), 80, "HTTP")],
    )];
    let routes = vec![route(
        "default",
        "app",
        vec![parent("web")],
        vec!["h.example.com"],
        vec![HTTPRouteRule {
            matches: vec![prefix_match("/")],
            backend_refs: vec![], // no backend → nothing to proxy
        }],
    )];

    let store = ConfigStore::load("seed", "").unwrap();
    install(&store, &classes, &gateways, &routes, CONTROLLER_NAME).expect("installs");
    let gen = store.current();
    assert!(gen.config.sites.is_empty(), "no routable rule → no site");
}

#[test]
fn malicious_route_fields_are_rejected_not_injected() {
    // Each of these HTTPRoutes carries a field that, if interpolated verbatim,
    // would inject Flow directives or an SSRF target. The controller must skip
    // the offending route entirely rather than emit unsafe config (security C1).
    let classes = vec![class("pulsate", CONTROLLER_NAME)];
    let gateways = vec![gateway(
        "default",
        "web",
        "pulsate",
        vec![listener("http", Some("good.example.com"), 80, "HTTP")],
    )];

    // 1) Newline-injection + a forged `site` block in the hostname.
    let newline_host = route(
        "default",
        "evil1",
        vec![parent("web")],
        vec!["evil.com\n}\nsite injected.com {\n  tls off"],
        vec![HTTPRouteRule {
            matches: vec![prefix_match("/")],
            backend_refs: vec![backend("svc", 80)],
        }],
    );

    // 2) `tls off` downgrade smuggled through a hostname with spaces.
    let tls_off_host = route(
        "default",
        "evil2",
        vec![parent("web")],
        vec!["host tls off"],
        vec![HTTPRouteRule {
            matches: vec![prefix_match("/")],
            backend_refs: vec![backend("svc", 80)],
        }],
    );

    // 3) SSRF: a backend pointing at the cloud metadata endpoint via metachars.
    let ssrf_backend = route(
        "default",
        "evil3",
        vec![parent("web")],
        vec!["good.example.com"],
        vec![HTTPRouteRule {
            matches: vec![prefix_match("/")],
            backend_refs: vec![backend("169.254.169.254) tls off proxy(http://evil", 80)],
        }],
    );

    // 4) Flow metacharacters in a path-match value.
    let bad_path = route(
        "default",
        "evil4",
        vec![parent("web")],
        vec!["good.example.com"],
        vec![HTTPRouteRule {
            matches: vec![prefix_match("/x ~> proxy(http://evil)")],
            backend_refs: vec![backend("svc", 80)],
        }],
    );

    // 5) Non-alphabetic method.
    let bad_method = route(
        "default",
        "evil5",
        vec![parent("web")],
        vec!["good.example.com"],
        vec![HTTPRouteRule {
            matches: vec![HTTPRouteMatch {
                path: Some(HTTPPathMatch {
                    match_type: "Exact".to_string(),
                    value: "/x".to_string(),
                }),
                method: Some("GET]\n  route /* ~> respond(status=200) [".to_string()),
            }],
            backend_refs: vec![backend("svc", 80)],
        }],
    );

    for evil in [
        newline_host,
        tls_off_host,
        ssrf_backend,
        bad_path,
        bad_method,
    ] {
        let routes = vec![evil];
        let text = to_flow(&classes, &gateways, &routes, CONTROLLER_NAME);
        // The only site that may appear is the legitimate listener host, and no
        // injected directive/target survives.
        assert!(
            !text.contains("injected.com"),
            "site injection leaked:\n{text}"
        );
        assert!(
            !text.contains("169.254.169.254"),
            "SSRF target leaked:\n{text}"
        );
        assert!(
            !text.contains("proxy(http://evil"),
            "metachar payload leaked:\n{text}"
        );
        assert!(
            !text.contains("\n  tls off") || text.contains("good.example.com"),
            "downgrade leaked:\n{text}"
        );
        // It must still compile into a valid (empty-of-evil) config.
        let store = ConfigStore::load("seed", "").unwrap();
        install(&store, &classes, &gateways, &routes, CONTROLLER_NAME).expect("safe install");
    }
}

#[test]
fn translation_is_deterministic() {
    let classes = vec![class("pulsate", CONTROLLER_NAME)];
    let gateways = vec![gateway(
        "default",
        "web",
        "pulsate",
        vec![listener("http", Some("d.example.com"), 80, "HTTP")],
    )];
    let routes = vec![route(
        "default",
        "app",
        vec![parent("web")],
        vec!["d.example.com"],
        vec![HTTPRouteRule {
            matches: vec![prefix_match("/x"), prefix_match("/y")],
            backend_refs: vec![backend("svc", 80)],
        }],
    )];

    let a = to_flow(&classes, &gateways, &routes, CONTROLLER_NAME);
    let b = to_flow(&classes, &gateways, &routes, CONTROLLER_NAME);
    assert_eq!(a, b, "translation must be byte-stable");

    // Installing twice produces the same snapshot id (content-addressed).
    let store = ConfigStore::load("seed", "").unwrap();
    install(&store, &classes, &gateways, &routes, CONTROLLER_NAME).unwrap();
    let id1 = store.current().snapshot.id();
    install(&store, &classes, &gateways, &routes, CONTROLLER_NAME).unwrap();
    let id2 = store.current().snapshot.id();
    assert_eq!(id1, id2);
}
